# Setup
title: 'the qt academy'
url: https://ivonzzhang.github.io/qt-academy/

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled

collections:
  'lectures':
    output: true
    permalink: /qt-academy/:collection/:title

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
